-- Future Supabase migration; NOT applied by this mock build.
-- Auth passwords remain owned by Supabase Auth. Never put them in profiles.
create extension if not exists pgcrypto;
create table public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 gip_code text not null unique check (gip_code ~ '^[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}$'),
 nickname text not null check (char_length(nickname) between 1 and 20),
 created_at timestamptz not null default now()
);
create table public.user_teams (
 user_id uuid not null references public.profiles(id) on delete cascade,
 team_id text not null,
 primary key (user_id, team_id)
);
create table public.user_leagues (
 user_id uuid not null references public.profiles(id) on delete cascade,
 league text not null check (league in ('KBO','NPB','MLB','CPBL')),
 primary key (user_id, league)
);
create table public.notification_settings (
 user_id uuid primary key references public.profiles(id) on delete cascade,
 game_start boolean not null default false,
 game_final boolean not null default false
);
create table public.reviews (
 id uuid primary key default gen_random_uuid(),
 user_id uuid not null references public.profiles(id) on delete cascade,
 kind text not null check (kind in ('line','visit')),
 game_id text,
 game_date date not null,
 matchup text not null check (char_length(matchup) between 1 and 100),
 venue text not null default '',
 content text not null check (char_length(trim(content)) > 0 and char_length(content) <= case when kind = 'line' then 100 else 3000 end),
 seat text not null default '',
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index reviews_user_date_idx on public.reviews(user_id, game_date desc);
alter table public.profiles enable row level security;
alter table public.user_teams enable row level security;
alter table public.user_leagues enable row level security;
alter table public.notification_settings enable row level security;
alter table public.reviews enable row level security;
-- GIP CODE is generated by a trusted server/auth trigger. Clients cannot assign or update it.
create policy profile_read on public.profiles for select to authenticated using (auth.uid() = id);
create policy profile_update on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);
revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
grant update(nickname) on public.profiles to authenticated;
create policy own_teams on public.user_teams for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy own_leagues on public.user_leagues for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy own_notifications on public.notification_settings for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy own_reviews on public.reviews for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
revoke all on public.user_teams, public.user_leagues, public.notification_settings, public.reviews from anon;
grant select, insert, update, delete on public.user_teams, public.user_leagues, public.notification_settings, public.reviews to authenticated;
create function public.set_review_updated_at() returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at = now(); new.user_id = old.user_id; new.created_at = old.created_at; return new; end;
$$;
create trigger review_updated before update on public.reviews for each row execute function public.set_review_updated_at();
