'use client';
import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { Star, CalendarDays, ChevronRight, ChevronLeft, ChevronDown, Plus, Copy, Check, Bell, Headphones, FileText, ShieldCheck, LogOut, Pencil, Trash2, X, ImagePlus } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Switch } from '@/components/ui/switch';
import { connected, getSchedule, sourceName, winter } from '@/lib/gip/live-baseball';
import { baseball, users } from '@/lib/gip/repositories';
import { addDays, dateLabel, koreaToday, team, TEAMS } from '@/lib/gip/catalog';
import { compareTeamNames, leagueLabel, orderedContinents, orderedLeagues } from '@/lib/gip/league-labels';
import { CONTINENTS, Continent, Game, LEAGUES, LEAGUES_BY_CONTINENT, League, Profile, Review, ReviewInput, Standing } from '@/lib/gip/types';
import { Woori, growth, growthIndex, type WooriPose } from './woori';
import { PrivacyContent, TermsContent } from './legal-content';
type Page = 'home'|'standings'|'records'|'my';
type Modal = 'profile'|'teams'|'leagues'|'notifications'|'support'|'terms'|'privacy'|'auth'|'calendar'|'editor'|'logout'|'detail'|'player'|null;
const nav = [{id:'home',label:'홈'},{id:'standings',label:'순위'},{id:'records',label:'기록'},{id:'my',label:'마이'}] as const;
function HandNavIcon({name}:{name:Page}) {
 const paths={
  home:<><path d="M3 11.2 11.8 3.7c.3-.3.7-.2 1 .1l8.1 7.5"/><path d="M5.5 10.1c-.2 4.1-.1 7.2.1 10.2 3.3.2 9.8.4 13.2 0l.2-10.2"/><path d="M10 20.2v-5.8c.9-.7 3-.7 4 .1l.1 5.6"/></>,
  standings:<><path d="M3.5 20.2c4.5.3 12.2.4 17.1-.1"/><path d="M5 18.6c-.2-2.1-.1-3.6.2-5.8l3.8-.1c.2 2.1.3 4 .1 5.9"/><path d="M10 18.5c-.2-4.2-.1-7.1.2-9.2h3.7c.2 3.2.3 6.3.1 9.1"/><path d="M15.1 18.6c-.1-2.5 0-4.5.3-6.8l3.7.1.1 6.7"/><path d="m11.2 5.2 1-2.2 1.1 2.2 2.3.3-1.8 1.4.5 2.2-2.1-1.1-2 1.1.5-2.2-1.8-1.4z"/></>,
  records:<><path d="M6.2 3.8c4.1-.3 8.4-.1 11.3.2l.2 15.7c-3.5-.3-8-.2-11.6.2-.4-4.7-.3-10.5.1-16.1Z"/><path d="M8.7 8.1c2.1-.2 4.5-.2 6.5.1M8.6 11.4c1.9-.1 4-.1 6.1.2M8.7 14.8c1.2-.1 2.4-.1 3.7 0"/><path d="m15.6 18.9 4.7-5.1 1.5 1.5-4.6 5-2.2.6z"/></>,
  my:<><path d="M12.2 4c-2.1-.3-3.9 1.5-4 4-.1 2.5 1.3 4.5 3.7 4.7 2.3.1 4-1.7 4.1-4 .1-2.4-1.4-4.5-3.8-4.7Z"/><path d="M5.1 20.4c-.2-4.2 2.9-6.5 6.8-6.6 4.3-.2 7.3 2.3 7.1 6.5-3.8.6-10.2.8-13.9.1Z"/></>
 };
 return <svg className="hand-nav-icon" viewBox="0 0 24 24" width="25" height="25" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}
function LeagueTabs({value,onChange,all=false,items=LEAGUES}:{value:string;onChange:(v:string)=>void;all?:boolean;items?:readonly string[]}) {
 const listRef=useRef<HTMLDivElement>(null);
 const options=all?['전체',...items]:items;
 useEffect(()=>{const list=listRef.current,active=list?.querySelector<HTMLElement>('[data-state="active"]');if(!list||!active)return;const area=list.getBoundingClientRect(),tab=active.getBoundingClientRect();if(tab.left<area.left)list.scrollBy({left:tab.left-area.left,behavior:'smooth'});else if(tab.right>area.right)list.scrollBy({left:tab.right-area.right,behavior:'smooth'});},[value]);
 return <Tabs className="league-tabs" value={value} onValueChange={onChange}><div className="league-tabs-row">{options.length>3&&<button type="button" className="tabs-arrow" aria-label="이전 항목 보기" onClick={()=>listRef.current?.scrollBy({left:-220,behavior:'smooth'})}><ChevronLeft size={17}/></button>}<TabsList ref={listRef} className="pills" aria-label="리그 선택">{options.map(l=><TabsTrigger key={l} value={l}>{LEAGUES.includes(l as League)?leagueLabel(l as League):l}</TabsTrigger>)}</TabsList>{options.length>3&&<button type="button" className="tabs-arrow" aria-label="다음 항목 보기" onClick={()=>listRef.current?.scrollBy({left:220,behavior:'smooth'})}><ChevronRight size={17}/></button>}</div></Tabs>;
}
function Empty({title,children,woori=false}:{title:string;children?:ReactNode;woori?:boolean}){return <div className="empty">{woori&&<Woori className="empty-woori"/>}<p>{title}</p>{children}</div>;}
function displayTeamName(name:string):ReactNode {return name;}
function GameCard({game,compact=false,ourGame=false,onClick}:{game:Game;compact?:boolean;ourGame?:boolean;onClick:()=>void}){const final=game.status==='final', live=game.status==='in_progress', postponed=game.status==='postponed';const start=game.timeTBD?'시간 미정':game.startsAt.slice(11,16);const status=game.statusLabel??(final?'FINAL':postponed?'경기 연기':live?(game.inning??'진행 중'):ourGame?'경기 전':game.timeTBD?'시간 미정':`${start} 시작`);return <button className={compact?'game-row':'game-card'} onClick={onClick} aria-label={`${team(game.awayId).short} 대 ${team(game.homeId).short}, ${final||live?`${game.awayScore} 대 ${game.homeScore}, ${status}`:postponed?status:start+' 경기 예정'}`}>
 {!compact&&<div className="game-meta"><span>{leagueLabel(game.league)}</span><span className={live?'live-status':''}>{status}</span></div>}
 <div className="scoreline"><span className="team-name">{compact?team(game.awayId).short:displayTeamName(team(game.awayId).name)}{!compact&&<small>원정</small>}</span><strong className={final||live?'score':'start-time'}>{final||live?<>{game.awayScore??'—'}<em>:</em>{game.homeScore??'—'}</>:compact?(postponed?status:start):<span className="versus">{postponed?status:start}</span>}</strong><span className="team-name">{compact?team(game.homeId).short:displayTeamName(team(game.homeId).name)}{!compact&&<small>홈</small>}</span>{compact&&<span className={live?'row-status live-status':'row-status'}>{status}</span>}</div>
 {!compact&&<div className="venue">{dateLabel(game.date)}<span>·</span>{game.venue}</div>}
 </button>;}
export function GipApp(){
 const [page,setPage]=useState<Page>('home'), [today,setToday]=useState(''), [date,setDate]=useState(''), [games,setGames]=useState<Game[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[retry,setRetry]=useState(0);
 const [profile,setProfile]=useState<Profile|null>(null),[ready,setReady]=useState(false),[reviews,setReviews]=useState<Review[]>([]),[modal,setModal]=useState<Modal>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[toast,setToast]=useState('');
 const [homeContinent,setHomeContinent]=useState<Continent>('아시아'),[homeLeague,setHomeLeague]=useState('전체'),[standingContinent,setStandingContinent]=useState<Continent>('아시아'),[league,setLeague]=useState<League>('KBO'),[season,setSeason]=useState(2026),[standing,setStanding]=useState<Standing[]>([]),[standingLoading,setStandingLoading]=useState(true),[group,setGroup]=useState(''),[recordTab,setRecordTab]=useState<'line'|'visit'>('line');
 const [draftTeams,setDraftTeams]=useState<string[]>([]),[draftLeagues,setDraftLeagues]=useState<League[]>([]),[pickerLeague,setPickerLeague]=useState<League>(orderedLeagues('아시아')[0]),[pickerContinent,setPickerContinent]=useState<Continent>('아시아'),[leagueContinent,setLeagueContinent]=useState<Continent>('아시아'),[authMode,setAuthMode]=useState<'signup'|'login'>('signup'),[nickname,setNickname]=useState(''),[password,setPassword]=useState(''),[code,setCode]=useState(''),[consent,setConsent]=useState(false);
 const [selectedGame,setSelectedGame]=useState<Game|null>(null),[editing,setEditing]=useState<Review|null>(null),[editorDate,setEditorDate]=useState(''),[editorGames,setEditorGames]=useState<Game[]>([]),[gameId,setGameId]=useState(''),[content,setContent]=useState(''),[venue,setVenue]=useState(''),[matchup,setMatchup]=useState(''),[seat,setSeat]=useState(''),[photoData,setPhotoData]=useState(''),[photoName,setPhotoName]=useState(''),[deleteConfirm,setDeleteConfirm]=useState(false);
 const [failedLeagues,setFailedLeagues]=useState<League[]>([]),[updatedAt,setUpdatedAt]=useState(''),[standingError,setStandingError]=useState(''),[editorError,setEditorError]=useState('');
 const [calendarMonth,setCalendarMonth]=useState(''),[expandedLeagues,setExpandedLeagues]=useState<League[]>([]);
 const teamIds=profile?.teamIds??[], interests=(profile?.leagues??[...LEAGUES]).filter(l=>LEAGUES.includes(l));
 const disconnectedFavorites=Array.from(new Set(teamIds.map(id=>team(id)?.league).filter((l):l is League=>Boolean(l)&&!connected(l))));
 function notify(text:string){setToast(text);}
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{const now=koreaToday();setToday(now);setDate(now);setEditorDate(now);users.current().then(async p=>{setProfile(p);if(p)setReviews(await users.reviews());}).catch(e=>setLoadError(e.message)).finally(()=>setReady(true));const readHash=()=>{const p=location.hash.slice(1);if(nav.some(n=>n.id===p))setPage(p as Page);};readHash();window.addEventListener('hashchange',readHash);return()=>window.removeEventListener('hashchange',readHash);},[]);
 useEffect(()=>{const refresh=()=>setToday(koreaToday());window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh);},[]);
 useEffect(()=>{if(!date)return;let active=true,running=false;setGames([]);setUpdatedAt('');setFailedLeagues([]);setLoading(true);setLoadError('');
 async function refresh(){if(running)return;running=true;try{const result=await getSchedule(date);if(active){setGames(result.games);setFailedLeagues(result.failed);setUpdatedAt(result.updatedAt);setLoadError('');setSelectedGame(old=>old?result.games.find(g=>g.id===old.id)??old:null);}}catch(e){if(active)setLoadError(e instanceof Error?e.message:'경기 조회 실패');}finally{running=false;if(active)setLoading(false);}}
 void refresh();const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},60000);return()=>{active=false;clearInterval(timer);};},[date,retry]);
 useEffect(()=>{let active=true;setStandingLoading(true);setStanding([]);setStandingError('');baseball.getStandings(league,season).then(rows=>{if(active){setStanding(rows);setGroup(league==='NPB'?'센트럴':rows.length?(rows[0].group??team(rows[0].teamId).group):'');}}).catch(e=>{if(active)setStandingError(connected(league)?'순위를 불러오지 못했어요. 다시 시도해 주세요.':e.message);}).finally(()=>{if(active)setStandingLoading(false);});return()=>{active=false;};},[league,season,retry]);
 useEffect(()=>{let active=true;setEditorGames([]);setEditorError('');if(modal==='editor'&&editorDate)baseball.getGames(editorDate).then(g=>{if(active)setEditorGames(g);}).catch(e=>{if(active)setEditorError(e.message);});return()=>{active=false;};},[editorDate,modal]);
 function navigate(p:Page){setPage(p);location.hash=p;window.scrollTo({top:0,behavior:'instant'});}
 function open(m:Modal){setError('');setDeleteConfirm(false);setModal(m);if(m==='profile')setNickname(profile?.nickname??'');if(m==='teams'){setDraftTeams([...teamIds]);setPickerContinent('아시아');setPickerLeague(orderedLeagues('아시아')[0]);}if(m==='leagues')setDraftLeagues([...interests]);if(m==='auth'){setPassword('');}if(m==='calendar')setCalendarMonth(date.slice(0,7));}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'다시 시도해 주세요.');}finally{setBusy(false);}}
 function requireProfile(){if(profile)return true;setAuthMode('signup');open('auth');return false;}
 async function savePreferences(){if(!profile){setAuthMode('signup');open('auth');return;}await run(async()=>{const next={...profile,...(modal==='teams'?{teamIds:draftTeams}:{leagues:draftLeagues})};setProfile(await users.update(next));setModal(null);notify('설정을 저장했어요.');});}
 function startRecord(review?:Review,game?:Game){if(!requireProfile())return;setEditing(review??null);setEditorDate(review?.date??game?.date??date);setGameId(review?.gameId??game?.id??'');setContent(review?.content??'');setVenue(review?.venue??game?.venue??'');setMatchup(review?.matchup??(game?`${team(game.awayId).short} vs ${team(game.homeId).short}`:''));setSeat(review?.seat??'');setPhotoData(review?.photoData??'');setPhotoName(review?.photoName??'');if(review)setRecordTab(review.kind);open('editor');}
 async function saveRecord(e:FormEvent){e.preventDefault();await run(async()=>{const picked=editorGames.find(g=>g.id===gameId);const input:ReviewInput={kind:recordTab,date:editorDate,gameId:gameId||null,matchup:picked?`${team(picked.awayId).short} ${picked.status==='final'?`${picked.awayScore} : ${picked.homeScore}`:'vs'} ${team(picked.homeId).short}`:matchup.trim(),venue:venue.trim(),content,seat:recordTab==='visit'?seat.trim():'',photoData:photoData||undefined,photoName:photoName||undefined};if(!input.matchup)throw Error('경기를 선택하거나 팀 이름을 입력해 주세요.');await users.saveReview(input,editing?.id);setReviews(await users.reviews());setModal(null);navigate('records');notify(editing?'기록을 수정했어요.':'좋은 경기를 기록했네!');});}
 function attachPhoto(file?:File){if(!file)return;if(!file.type.startsWith('image/')){setError('이미지 파일만 첨부할 수 있어요.');return;}if(file.size>1_500_000){setError('사진은 1.5MB 이하로 첨부해 주세요.');return;}const reader=new FileReader();reader.onload=()=>{setPhotoData(String(reader.result));setPhotoName(file.name);setError('');};reader.onerror=()=>setError('사진을 읽지 못했어요.');reader.readAsDataURL(file);}
 const groups=Array.from(new Set(standing.map(s=>s.group??team(s.teamId).group))).sort((a,b)=>league==='NPB'?(a==='센트럴'?-1:b==='센트럴'?1:0):0);const selectedRows=standing.filter(s=>(s.group??team(s.teamId).group)===group);
 const myGames=games.filter(g=>teamIds.includes(g.awayId)||teamIds.includes(g.homeId));
 const continentLeagues=orderedLeagues(homeContinent);
 const standingLeagues=orderedLeagues(standingContinent);
 const allGames=games.filter(g=>continentLeagues.includes(g.league)&&interests.includes(g.league)&&(homeLeague==='전체'||g.league===homeLeague));
 const level=growthIndex(reviews.length), stage=growth[level], nextStage=growth[level+1];
 const finished=myGames.filter(g=>g.status==='final');
 const won=finished.some(g=>g.awayScore!==null&&g.homeScore!==null&&((teamIds.includes(g.awayId)&&g.awayScore>g.homeScore)||(teamIds.includes(g.homeId)&&g.homeScore>g.awayScore)));
 const lost=finished.some(g=>g.awayScore!==null&&g.homeScore!==null&&((teamIds.includes(g.awayId)&&g.awayScore<g.homeScore)||(teamIds.includes(g.homeId)&&g.homeScore<g.awayScore)));
 const homePose=won?'happy':lost?'sad':'blanket';
 const titles:Record<Exclude<Modal,null>,string>={player:'나의 야구선수',profile:'프로필 수정',teams:'우리 집 선택하기',leagues:'관심 리그',notifications:'알림 설정',support:'고객센터',terms:'이용약관',privacy:'개인정보처리방침',auth:authMode==='signup'?'우리 집 만들기':'다시 우리 집으로',calendar:'날짜 선택',editor:editing?'기록 수정':recordTab==='line'?'한줄평 남기기':'직관 후기 남기기',logout:'로그아웃',detail:'경기 정보'};
 const descriptions:Record<Exclude<Modal,null>,string>={player:'매일의 야구를 쌓아서 우리집을 완성해요.',profile:'집에서 사용할 이름을 변경해 주세요.',teams:'함께 응원할 팀을 모두 골라 주세요.',leagues:'전체 경기에서 보고 싶은 리그를 골라 주세요.',notifications:'알림 설정을 저장할 수 있어요. 실제 알림 발송은 아직 지원하지 않아요.',support:'GIP 서비스 이용 안내',terms:'GIP 서비스 이용약관',privacy:'GIP 개인정보 처리 방식',auth:'GIP 계정과 기록은 이 브라우저에 저장돼요.',calendar:'모든 경기 시간은 한국 시간 기준이에요.',editor:'오늘의 야구를 내 말로 남겨 보세요.',logout:'저장한 기록은 이 브라우저에 남아 있어요.',detail:'제공처의 경기 정보 · 한국 시간 기준 · 반영 지연 가능'};
 if(!today)return <div className="app-shell"><header className="header"><span className="wordmark">GIP</span></header><main className="main"><p role="status">우리 집을 열고 있어요.</p></main></div>;
 return <div className="app-shell"><header className="header"><div className="brand-block"><div className="brand-line"><button className="wordmark" onClick={()=>navigate('home')} aria-label="GIP 홈">GIP</button></div><p className="brand-tagline">야구가 있는 곳, 어디든 우리 집.</p></div><button className="header-account" onClick={()=>{if(profile)navigate('my');else{setAuthMode('signup');open('auth');}}}>{profile?'우리 집 / 마이':'시작하기 / 회원가입'}</button></header>
 <main id="main" className="main">
 {page==='home'&&<><h1 className="sr-only">우리 집 야구 경기</h1><div className="home-companion"><Woori pose={homePose} label={won?'응원팀의 승리를 기뻐하는 우리':lost?'이불 속에 숨은 우리':'야구공을 안고 기다리는 우리'}/>{(won||lost)&&<span>{won?'좋은 경기였네!':'다음 경기도 함께해요.'}</span>}</div><div className="date-bar"><button className="date-arrow" aria-label="이전 날짜" onClick={()=>setDate(addDays(date,-1))}><ChevronLeft size={24}/></button><button className="date-picker" onClick={()=>open('calendar')} aria-label={`날짜 선택, ${date}`}><CalendarDays size={20}/><span>{date}</span></button><button className="date-arrow" aria-label="다음 날짜" onClick={()=>setDate(addDays(date,1))}><ChevronRight size={24}/></button></div>

 <section><div className="section-heading"><h2>우리 집 경기</h2><button onClick={()=>open('teams')} aria-label="우리 집 팀 설정"><span>팀 설정</span><ChevronRight size={18}/></button></div>{loading?<Empty title="경기를 불러오고 있어요."/>:loadError?<Empty title={loadError}><button onClick={()=>setRetry(r=>r+1)}>다시 시도</button></Empty>:myGames.length?<div className="home-games">{myGames.map(g=><GameCard key={g.id} game={g} ourGame onClick={()=>{setSelectedGame(g);open('detail');}}/>)}</div>:<Empty title={teamIds.length?'연결된 데이터에서 우리 집 경기가 없어요.':'우리 집에 응원팀을 초대해 주세요.'}><button className="text-action" onClick={()=>open('teams')}>우리 집 설정 <ChevronRight size={16}/></button></Empty>}</section>
 {disconnectedFavorites.length>0&&<p className="footnote">{disconnectedFavorites.map(leagueLabel).join(', ')} 데이터는 연결 준비 중이에요.</p>}
 <section className="all-section">
  <div className="section-heading"><h2>전체 경기</h2><span className="muted">{allGames.length}경기</span></div>
  <LeagueTabs value={homeContinent} items={orderedContinents} onChange={v=>{const c=v as Continent;setHomeContinent(c);setHomeLeague('전체');setExpandedLeagues([]);}}/>
  <LeagueTabs value={homeLeague} all items={continentLeagues} onChange={v=>{setHomeLeague(v);if(v==='전체')setExpandedLeagues([]);}}/>
  <p className="footnote">{continentLeagues.filter(l=>!connected(l)&&(homeLeague==='전체'||homeLeague===l)).map(leagueLabel).join(', ')}{continentLeagues.some(l=>!connected(l)&&(homeLeague==='전체'||homeLeague===l))&&' · 데이터 연결 준비 중'}</p><div className="all-games">{!loading&&!loadError&&(allGames.length?continentLeagues.filter(l=>allGames.some(g=>g.league===l)).map(l=>{
   const leagueGames=allGames.filter(g=>g.league===l);
   const collapsed=homeLeague==='전체'&&!expandedLeagues.includes(l);
   return <div className="all-league" key={l}>
    {homeLeague==='전체'&&<button className="league-toggle" aria-expanded={!collapsed} aria-controls={`league-games-${LEAGUES.indexOf(l)}`} onClick={()=>setExpandedLeagues(prev=>prev.includes(l)?prev.filter(item=>item!==l):[...prev,l])}><span>{leagueLabel(l)}</span><span className="league-toggle-meta">{leagueGames.length}경기 <ChevronDown size={17} className={collapsed?'':'expanded'}/></span></button>}
    <div id={`league-games-${LEAGUES.indexOf(l)}`} hidden={collapsed}>{leagueGames.map(g=><GameCard key={g.id} game={g} compact onClick={()=>{setSelectedGame(g);open('detail');}}/>)}</div>
   </div>;
  }):<Empty title={interests.includes(homeLeague as League)||homeLeague==='전체'?'표시할 경기가 없어요.':'관심 리그에서 제외한 리그예요.'}><button className="text-action" onClick={()=>open('leagues')}>관심 리그 설정</button></Empty>)}</div>
 </section><p className="footnote">네이버 스포츠 · Yahoo! JAPAN 스포나비 · MLB Stats API · 한국 시간 기준 · 60초마다 확인{updatedAt&&` · ${updatedAt} 갱신`}</p>{failedLeagues.length>0&&<p className="footnote" role="status">{failedLeagues.map(leagueLabel).join(', ')} 조회 실패 · 일부 경기 누락 가능</p>}<p className="footnote"><button onClick={()=>setRetry(r=>r+1)}>새로고침</button></p></>}
 {page==='standings'&&<>
  <div className="page-title"><h1>순위</h1></div>
  <div className="standing-continent"><LeagueTabs value={standingContinent} items={orderedContinents} onChange={v=>{const c=v as Continent;setStandingContinent(c);setLeague(orderedLeagues(c)[0]);setGroup('');}}/></div>
  <div className="standing-controls"><LeagueTabs value={league} items={standingLeagues} onChange={v=>setLeague(v as League)}/><select className="season-select" aria-label="시즌 선택" value={season} onChange={e=>setSeason(Number(e.target.value))}>{[2026,2025,2024,2023].map(y=><option key={y} value={y}>{winter(league)?`${y}–${String(y+1).slice(2)}`:y} 시즌</option>)}</select></div>
  {groups.length>1&&<div className="groups" aria-label="지구 선택">{groups.map(g=><button key={g} className={g===group?'active':''} aria-pressed={g===group} onClick={()=>setGroup(g)}>{g}</button>)}</div>}
  {standingLoading?<div className="standing-empty"><Empty title="순위를 불러오고 있어요."/></div>:standingError?<Empty title={standingError}>{connected(league)&&<button onClick={()=>setRetry(r=>r+1)}>다시 시도</button>}</Empty>:standing.length?<><div className="standing-card"><div className="table-scroll"><table><caption className="sr-only">{season} {leagueLabel(league)} {group} 정규시즌 순위</caption><thead><tr>{['#','팀','경기','승','패','무','승률','게임차'].map(t=><th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{selectedRows.map((r,i)=><tr key={r.teamId} className={teamIds.includes(r.teamId)?'our-team':''}><td>{i+1}</td><th scope="row">{team(r.teamId).short}</th><td>{r.played}</td><td>{r.wins}</td><td>{r.losses}</td><td>{r.draws}</td><td>{r.percentage.toFixed(3).replace(/^0/,'')}</td><td>{r.gamesBehind?r.gamesBehind.toFixed(1):'—'}</td></tr>)}</tbody></table></div></div><p className="footnote">{sourceName(league)} · 정규시즌 순위 · 제공처 반영 지연 가능<br/><button onClick={()=>setRetry(r=>r+1)}>순위 새로고침</button></p></>:<div className="standing-empty"><Empty title={`${season} 시즌 ${leagueLabel(league)} 순위가 아직 제공되지 않았어요.`}><p className="muted">시즌 시작 전이거나 제공처에 해당 시즌 데이터가 없을 수 있어요.</p></Empty></div>}
 </>}
 {page==='records'&&<><div className="page-title"><h1>기록</h1><button className="icon-button" onClick={()=>startRecord()} aria-label="기록 작성"><Plus/></button></div><button className="companion-strip" onClick={()=>open('player')}><Woori pose={(level+1) as WooriPose} label={`Lv.${level+1} ${stage.name} 우리`}/><span><strong>우리와 함께 쌓은 {reviews.length}개의 기록</strong><small>Lv.{level+1} · {stage.name}</small></span><ChevronRight size={18}/></button><Tabs value={recordTab} onValueChange={v=>setRecordTab(v as 'line'|'visit')}><TabsList className="record-tabs"><TabsTrigger value="line">한줄평</TabsTrigger><TabsTrigger value="visit">직관 후기</TabsTrigger></TabsList></Tabs><div className="records">{reviews.filter(r=>r.kind===recordTab).length?reviews.filter(r=>r.kind===recordTab).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt)).map(r=><button className="record-card" key={r.id} onClick={()=>startRecord(r)}>{r.photoData&&<img className="record-photo" src={r.photoData} alt={r.photoName||`${r.matchup} 기록 사진`}/>}<div className="record-meta"><span>{r.date.replaceAll('-','. ')}</span><span>{r.venue}</span></div><div className="record-match"><strong>{r.matchup}</strong><ChevronRight size={18}/></div><p>{r.content}</p>{r.seat&&<span className="seat">{r.seat}</span>}</button>):<Empty woori title={recordTab==='line'?'아직 남긴 한줄평이 없어요.':'아직 남긴 직관 후기가 없어요.'}><p className="muted">{recordTab==='line'?'경기를 보고 떠오른 한마디를 남겨 주세요.':'구장에 다녀온 하루를 기록해 보세요.'}</p><button className="primary" onClick={()=>startRecord()}>{recordTab==='line'?'첫 한줄평 남기기':'첫 직관 후기 남기기'}</button></Empty>}</div><button className="floating-add" onClick={()=>startRecord()} aria-label="새 기록 작성"><Plus size={25}/></button><p className="footnote">사진을 포함한 기록은 현재 브라우저에 저장됩니다.</p></>}
 {page==='my'&&<><h1 className="sr-only">마이</h1><div className="profile-card"><div className="profile-avatar">{profile?.nickname.slice(0,1)??'집'}</div><div className="profile-info"><h2>{profile?.nickname??'야구집사'}</h2>{profile?<button className="profile-code" onClick={()=>navigator.clipboard.writeText(profile.gipCode).then(()=>notify('GIP CODE를 복사했어요.')).catch(()=>notify(`GIP CODE: ${profile.gipCode}`))} aria-label="GIP CODE 복사">GIP CODE: <strong>{profile.gipCode}</strong></button>:<p>나만의 집을 만들어 보세요.</p>}</div><button className="profile-edit" onClick={()=>{if(requireProfile())open('profile');}}>{profile?'프로필 수정':'가입 / 로그인'}</button></div><button className="player-card" onClick={()=>open('player')}><div><span className="eyebrow">나의 야구선수</span><strong>우리 <small>Lv.{level+1} · {stage.name}</small></strong><p>매일의 야구를 쌓아서 우리집을 완성해요.</p><span className="player-link">조금씩 성장하고 있어요 <ChevronRight size={15}/></span></div><Woori pose={(level+1) as WooriPose} label={`${stage.name} 우리`}/></button><section className="favorite-card"><h2><Star size={21}/>우리 집 선택하기 <span>(우리 집 경기 연동)</span></h2><div className="favorite-chips">{[...teamIds].filter(id=>team(id)).sort((a,b)=>compareTeamNames(team(a).name,team(b).name)).map(id=><button key={id} className={teamIds.includes(id)?'chosen':''} aria-pressed={teamIds.includes(id)} disabled={busy} onClick={()=>{if(!requireProfile())return;run(async()=>{const next=teamIds.includes(id)?teamIds.filter(t=>t!==id):[...teamIds,id];setProfile(await users.update({...profile!,teamIds:next}));});}}><span>{team(id).name}</span>{teamIds.includes(id)?<Check size={16}/>:<Plus size={16}/>}</button>)}{teamIds.length===0&&<p className="muted">아직 선택한 팀이 없어요.</p>}</div><button className="favorite-more" onClick={()=>open('teams')}>전체 팀에서 선택<ChevronRight size={16}/></button></section><button className="interest-row" onClick={()=>open('leagues')}><span>관심 리그</span><span>{interests.length}개 리그 <ChevronRight size={18}/></span></button><div className="settings-list">{[{m:'notifications',label:'알림 설정',Icon:Bell},{m:'support',label:'고객센터',Icon:Headphones},{m:'terms',label:'이용약관',Icon:FileText},{m:'privacy',label:'개인정보처리방침',Icon:ShieldCheck},{m:profile?'logout':'auth',label:profile?'로그아웃':'로그인 / 회원가입',Icon:LogOut}].map(({m,label,Icon})=><button key={m} onClick={()=>{if(m==='auth')setAuthMode('login');open(m as Modal);}}><Icon size={21}/><span>{label}</span><ChevronRight size={18}/></button>)}</div><p className="footnote">GIP 정식 서비스 · 계정과 기록은 이 브라우저에 저장</p></>}

 </main><nav className="bottom-nav" aria-label="하단 메뉴">{nav.map(({id,label})=><button key={id} className={page===id?'active':''} aria-current={page===id?'page':undefined} onClick={()=>navigate(id)}><HandNavIcon name={id}/><span>{label}</span></button>)}</nav>
 {toast&&<div role="status" className="toast">{toast==='좋은 경기를 기록했네!'?<Woori pose="ball" className="toast-woori" label="야구공을 안고 기뻐하는 우리"/>:<Check size={16}/>}<span>{toast}</span></div>}
 <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal(null);}}><DialogContent className="gip-dialog"><DialogHeader><DialogTitle>{modal?titles[modal]:''}</DialogTitle><DialogDescription>{modal?descriptions[modal]:''}</DialogDescription></DialogHeader>
 {modal==='player'&&<div className="player-panel"><Woori pose={(level+1) as WooriPose} label={`Lv.${level+1} ${stage.name} 우리`}/><h3>우리 · Lv.{level+1}</h3><strong>{stage.name}</strong><p>매일의 야구를 쌓아서 우리집을 완성해요.</p><div className="growth-summary"><span>함께 남긴 기록 <strong>{reviews.length}개</strong></span>{nextStage?<><progress aria-label="다음 성장 단계까지 기록" value={reviews.length-stage.count} max={nextStage.count-stage.count}/><small>다음 만남은 {nextStage.count}개의 기록에서 · {nextStage.name}</small></>:<p>앞으로의 야구도 함께해요.</p>}</div><ol className="growth-list">{growth.map((g,i)=><li key={g.name} className={i===level?'current':i>level?'locked':''} aria-current={i===level?'step':undefined}>{i<=level?<Woori pose={(i+1) as WooriPose} label={`${g.name} 해금`}/>:<span className="locked-pose" aria-label="아직 만나지 않은 모습">{i+1}</span>}<span><small>Lv.{i+1}</small><strong>{g.name}</strong><small>{g.count}개 기록 {i===level?'· 지금의 우리':i<level?'· 함께한 모습':''}</small></span>{i<level&&<Check size={15}/>}</li>)}</ol></div>}
 {modal==='profile'&&profile&&<form className="form" onSubmit={e=>{e.preventDefault();run(async()=>{if(!nickname.trim())throw Error('닉네임을 입력해 주세요.');setProfile(await users.update({...profile,nickname:nickname.trim()}));setModal(null);notify('프로필을 수정했어요.');});}}><label>닉네임<input required maxLength={20} value={nickname} onChange={e=>setNickname(e.target.value)} autoComplete="nickname"/></label><button className="primary" disabled={busy}>저장하기</button></form>}
 {modal==='teams'&&<><LeagueTabs value={pickerContinent} items={orderedContinents} onChange={v=>{const c=v as Continent;setPickerContinent(c);setPickerLeague(orderedLeagues(c)[0]);}}/><LeagueTabs value={pickerLeague} items={orderedLeagues(pickerContinent)} onChange={v=>setPickerLeague(v as League)}/><div className="team-picker">{TEAMS.filter(t=>t.league===pickerLeague).sort((a,b)=>compareTeamNames(a.name,b.name)).map(t=><button key={t.id} className={draftTeams.includes(t.id)?'chosen':''} aria-pressed={draftTeams.includes(t.id)} onClick={()=>setDraftTeams(prev=>prev.includes(t.id)?prev.filter(id=>id!==t.id):[...prev,t.id])}><span>{t.name}</span>{draftTeams.includes(t.id)?<Check size={18}/>:<Plus size={18}/>}</button>)}</div><div className="modal-footer"><span>{draftTeams.length}팀 선택</span><button className="primary" disabled={busy||!ready} onClick={savePreferences}>{profile?'저장하기':'가입하고 저장하기'}</button></div></>}
 {modal==='leagues'&&<><LeagueTabs value={leagueContinent} items={orderedContinents} onChange={v=>setLeagueContinent(v as Continent)}/><div className="league-picker">{orderedLeagues(leagueContinent).map(l=><button key={l} className={draftLeagues.includes(l)?'chosen':''} aria-pressed={draftLeagues.includes(l)} onClick={()=>setDraftLeagues(p=>p.includes(l)?p.filter(a=>a!==l):[...p,l])}><span><small>{leagueContinent}</small>{leagueLabel(l)}</span>{draftLeagues.includes(l)?<Check size={20}/>:<Plus size={20}/>}</button>)}</div><button className="primary" disabled={busy||!ready} onClick={savePreferences}>{profile?'저장하기':'가입하고 저장하기'}</button></>}
 {modal==='notifications'&&<div className="notification-settings">{(['start','final'] as const).map((n)=><label key={n}><span>{n==='start'?'우리 집 경기 시작':'우리 집 경기 결과'}</span><Switch checked={profile?.notifications[n]??false} disabled={busy} onCheckedChange={checked=>{if(!requireProfile())return;run(async()=>{setProfile(await users.update({...profile!,notifications:{...profile!.notifications,[n]:checked}}));});}} aria-label={n==='start'?'경기 시작 알림':'경기 결과 알림'}/></label>)}<p className="notice">현재는 설정만 저장돼요. 브라우저 알림은 발송되지 않아요.</p></div>}
 {modal==='auth'&&<form className="form" onSubmit={e=>{e.preventDefault();run(async()=>{if(authMode==='signup'&&!consent)throw Error('이용약관과 개인정보처리방침에 동의해 주세요.');const p=authMode==='signup'?await users.signUp(nickname,password):await users.signIn(code,password);setProfile(p);setReviews(await users.reviews());setPassword('');if(authMode==='signup'){setDraftTeams(draftTeams);setModal('teams');notify('5자리 GIP CODE가 만들어졌어요. 마이에서 확인해 주세요.');}else{setModal(null);notify('우리 집에 돌아온 걸 환영해요.');}});}}><Tabs value={authMode} onValueChange={v=>{setAuthMode(v as 'signup'|'login');setError('');}}><TabsList className="record-tabs"><TabsTrigger value="signup">회원가입</TabsTrigger><TabsTrigger value="login">로그인</TabsTrigger></TabsList></Tabs>{authMode==='signup'?<label>닉네임<input required maxLength={20} value={nickname} onChange={e=>setNickname(e.target.value)} autoComplete="nickname" placeholder="집에서 사용할 이름"/></label>:<label>GIP CODE<input required inputMode="numeric" maxLength={9} value={code} onChange={e=>setCode(e.target.value)} autoComplete="username" placeholder="예: 12345"/></label>}<label>비밀번호<input type="password" required minLength={8} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={authMode==='signup'?'new-password':'current-password'} placeholder="8자 이상"/></label><p className="notice">GIP 계정은 현재 이 브라우저에만 저장돼요. 다른 곳에서 쓰는 비밀번호는 사용하지 마세요. 브라우저 데이터를 지우면 계정과 기록도 삭제돼요.</p>{authMode==='signup'&&<label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/><span><a href="/terms" target="_blank" rel="noopener noreferrer">이용약관</a>과 <a href="/privacy" target="_blank" rel="noopener noreferrer">개인정보처리방침</a>에 동의해요.</span></label>}<button className="primary" disabled={busy||!ready}>{busy?'처리 중…':authMode==='signup'?'5자리 GIP CODE 만들기':'로그인'}</button>{authMode==='login'&&<p className="muted">가입한 브라우저에서 로그인해 주세요. 기존 영문 GIP CODE도 계속 로그인할 수 있어요.</p>}</form>}
 {modal==='calendar'&&<div className="calendar-panel"><div className="calendar-heading"><button className="icon-button" aria-label="이전 달" onClick={()=>{const d=new Date(calendarMonth+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()-1);setCalendarMonth(d.toISOString().slice(0,7));}}><ChevronLeft/></button><strong>{calendarMonth.replace('-','년 ')}월</strong><button className="icon-button" aria-label="다음 달" onClick={()=>{const d=new Date(calendarMonth+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+1);setCalendarMonth(d.toISOString().slice(0,7));}}><ChevronRight/></button></div><div className="calendar-grid">{['일','월','화','수','목','금','토'].map(d=><span className="weekday" key={d}>{d}</span>)}{Array.from({length:new Date(calendarMonth+'-01T12:00:00Z').getUTCDay()},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:new Date(Number(calendarMonth.slice(0,4)),Number(calendarMonth.slice(5)),0).getDate()},(_,i)=>{const day=calendarMonth+'-'+String(i+1).padStart(2,'0');return <button key={day} className={day===date?'selected':day===today?'is-today':''} aria-label={dateLabel(day)} aria-pressed={day===date} onClick={()=>{setDate(day);setModal(null);}}>{i+1}</button>;})}</div><p className="notice">경기 데이터는 제공처에서 확인 가능한 날짜에 표시돼요.</p></div>}
 {modal==='detail'&&selectedGame&&<><GameCard game={selectedGame} onClick={()=>{}}/><dl className="game-details"><div><dt>리그</dt><dd>{leagueLabel(selectedGame.league)}</dd></div><div><dt>구장</dt><dd>{selectedGame.venue}</dd></div><div><dt>시작 시간</dt><dd>{dateLabel(selectedGame.date)} {selectedGame.timeTBD?'시간 미정':selectedGame.startsAt.slice(11,16)}</dd></div></dl><button className="primary" onClick={()=>startRecord(undefined,selectedGame)}>이 경기 기록 남기기 <Pencil size={17}/></button></>}
 {modal==='editor'&&editorError&&<p className="footnote" role="status">{editorError}</p>}
 {modal==='editor'&&<form className="form" onSubmit={saveRecord}><label>경기 날짜<input type="date" required max={today} value={editorDate} onChange={e=>{setEditorDate(e.target.value);setGameId('');setMatchup('');setVenue('');}}/></label><label>경기<select value={gameId} onChange={e=>{const g=editorGames.find(g=>g.id===e.target.value);setGameId(e.target.value);setVenue(g?.venue??'');setMatchup(g?`${team(g.awayId).short} vs ${team(g.homeId).short}`:'');}}><option value="">직접 입력</option>{editorGames.map(g=><option key={g.id} value={g.id}>{leagueLabel(g.league)} · {team(g.awayId).short} vs {team(g.homeId).short}</option>)}</select></label>{!gameId&&<label>경기 팀<input required maxLength={100} value={matchup} onChange={e=>setMatchup(e.target.value)} placeholder="예: 롯데 vs 한화"/></label>}<label>구장<input maxLength={100} required={recordTab==='visit'} value={venue} onChange={e=>setVenue(e.target.value)} placeholder="예: 사직야구장"/></label>{recordTab==='visit'&&<label>좌석 <span className="muted">선택</span><input maxLength={100} value={seat} onChange={e=>setSeat(e.target.value)} placeholder="예: 1루 내야 123블록"/></label>}<label>{recordTab==='line'?'한줄평':'직관 후기'}<textarea required rows={recordTab==='line'?3:6} maxLength={recordTab==='line'?100:3000} value={content} onChange={e=>setContent(e.target.value)} placeholder={recordTab==='line'?'오늘의 경기를 한마디로.':'구장의 분위기부터 기억하고 싶은 순간까지.'}/><span className="char-count">{content.length} / {recordTab==='line'?100:3000}</span></label><div className="photo-field"><span>사진 <small>선택 · 1.5MB 이하</small></span>{photoData?<div className="photo-preview"><img src={photoData} alt="첨부 사진 미리보기"/><button type="button" aria-label="첨부 사진 삭제" onClick={()=>{setPhotoData('');setPhotoName('');}}><X size={18}/></button></div>:<label className="photo-picker"><ImagePlus size={20}/>사진 첨부<input type="file" accept="image/*" onChange={e=>attachPhoto(e.target.files?.[0])}/></label>}</div><button className="primary" disabled={busy}>{busy?'저장 중…':'저장하기'}</button>{editing&&(deleteConfirm?<div className="delete-confirm"><p>이 기록을 삭제할까요? 되돌릴 수 없어요.</p><button type="button" className="danger" disabled={busy} onClick={()=>run(async()=>{await users.deleteReview(editing.id);setReviews(await users.reviews());setModal(null);notify('기록을 삭제했어요.');})}>삭제 확인</button><button type="button" onClick={()=>setDeleteConfirm(false)}>취소</button></div>:<button type="button" className="delete-button" onClick={()=>setDeleteConfirm(true)}><Trash2 size={16}/>기록 삭제</button>)}</form>}
 {modal==='logout'&&<div className="form"><p>다시 로그인하려면 GIP CODE와 비밀번호가 필요해요.</p><strong className="logout-code">{profile?.gipCode}</strong><button className="primary" disabled={busy} onClick={()=>run(async()=>{await users.signOut();setProfile(null);setReviews([]);setModal(null);notify('로그아웃했어요.');})}>로그아웃</button></div>}
 {modal==='support'&&<div className="prose"><h3>경기와 순위가 실제와 달라요.</h3><p>MLB·LMB·LIDOM·LBPRC·LVBP·ABL은 MLB Stats API에서 가져와요. 홈은 60초마다 확인하며 제공처에 따라 반영이 늦을 수 있어요. KBO는 네이버 스포츠, NPB는 Yahoo! JAPAN 스포나비에서 가져와요. CPBL 순위는 CPBL 공식 팀별 기록의 상·하반기를 합산해요. 나머지 리그는 연결 준비 중이에요.</p><h3>다른 기기에서 기록이 안 보여요.</h3><p>GIP 계정과 기록은 가입한 브라우저에만 저장돼요. 다른 기기와 동기화되지 않고, 브라우저 데이터를 삭제하면 복구할 수 없어요.</p><h3>저장된 데이터를 지우고 싶어요.</h3><p>브라우저 설정에서 이 사이트의 저장 데이터를 삭제하면 계정, 팀 설정, 후기가 모두 삭제돼요. 삭제 후 복구는 지원하지 않아요.</p><h3>문의 접수</h3><p>공개 문의 채널을 준비 중이에요. 현재 이 화면에서는 운영자에게 메시지를 보낼 수 없어요.</p></div>}
 {modal==='terms'&&<TermsContent/>}
 {modal==='privacy'&&<PrivacyContent/>}
 {error&&<p role="alert" className="error">{error}</p>}
 </DialogContent></Dialog>
 </div>;
}
